import { useState } from 'react';
import { Alert, Linking, Platform, Pressable, View } from 'react-native';
import { ArrowRight, Bell, Check, CheckCircle2, Clock3, Hospital, LifeBuoy, LockKeyhole, MapPin, Navigation, Phone, Plus, Route, ShieldCheck, Timer, X } from 'lucide-react-native';
import { apiRequest } from './api';
import { TimerClock } from './Dashboard';
import type { ScreenProps } from './models';
import { Avatar, Badge, Button, Card, Empty, Field, Note, PageHeading, SectionTitle, T, c, dateLabel, s, statusLabel, timeLabel } from './ui';

export async function openLink(url: string) {
  try { await Linking.openURL(url); } catch { Alert.alert('Could not open', 'Please open your phone or maps app directly.'); }
}
function mapsSearch(query: string) {
  const encoded = encodeURIComponent(query);
  return Platform.OS === 'ios' ? `https://maps.apple.com/?q=${encoded}` : `https://www.google.com/maps/search/?api=1&query=${encoded}`;
}

function Choices({ options, value, onChange }: { options: number[]; value: number; onChange: (value: number) => void }) {
  return <View style={[s.row, { gap: 8, flexWrap: 'wrap' }]}>{options.map(minutes => <Pressable key={minutes} accessibilityRole="button" accessibilityState={{ selected: minutes === value }} onPress={() => onChange(minutes)} style={{ flex: 1, minWidth: 46, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 11, borderWidth: 1, borderColor: value === minutes ? c.pine2 : c.line, backgroundColor: value === minutes ? c.mint : c.white }}><T kind="label" style={{ color: c.pine }}>{minutes}m</T></Pressable>)}</View>;
}

export function JourneyScreen({ data, busy, run }: ScreenProps) {
  const [creating, setCreating] = useState(false);
  const [form, setForm] = useState({ title: '', origin: '', destination: '' });
  const [minutes, setMinutes] = useState(45);
  const [contactIds, setContactIds] = useState<string[]>([]);
  const patch = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }));
  const save = () => void run(async () => {
    await apiRequest('/journeys', { method: 'POST', body: JSON.stringify({ ...form, expectedArrival: new Date(Date.now() + minutes * 60000).toISOString(), contactIds }) });
    setCreating(false); setForm({ title: '', origin: '', destination: '' }); setContactIds([]);
  }, 'Journey saved. Press Start journey when you are ready.');
  return <>
    <PageHeading eyebrow="Move with confidence" title="Safe journeys" description="A familiar route. A little extra support. Plan your journey and check in along the way." />
    <Button title={creating ? 'Close journey form' : 'Plan a journey'} icon={creating ? X : Plus} tone={creating ? 'outline' : 'primary'} onPress={() => setCreating(!creating)} />
    {creating && <Card><SectionTitle eyebrow="Your next arrival" title="Plan a safe journey" /><Field label="Journey name" placeholder="Evening class" value={form.title} onChangeText={text => patch('title', text)} maxLength={80} /><Field label="Starting point" placeholder="Where are you leaving from?" value={form.origin} onChangeText={text => patch('origin', text)} maxLength={160} /><Field label="Destination" placeholder="Where are you heading?" value={form.destination} onChangeText={text => patch('destination', text)} maxLength={160} /><T kind="label">Arriving in</T><Choices options={[15, 30, 45, 60]} value={minutes} onChange={setMinutes} /><T kind="label">Your circle for this journey</T>{data.contacts.filter(contact => contact.verified).map(contact => <Pressable key={contact.id} accessibilityRole="checkbox" accessibilityState={{ checked: contactIds.includes(contact.id) }} onPress={() => setContactIds(current => current.includes(contact.id) ? current.filter(id => id !== contact.id) : [...current, contact.id])} style={[s.row, { paddingVertical: 8 }]}><Avatar name={contact.name} size={34} /><T kind="label" style={s.flex}>{contact.name}</T><View style={{ width: 24, height: 24, borderRadius: 7, borderWidth: 1, borderColor: c.line, backgroundColor: contactIds.includes(contact.id) ? c.pine : c.white, alignItems: 'center', justifyContent: 'center' }}>{contactIds.includes(contact.id) && <Check size={15} color={c.white} />}</View></Pressable>)}{!data.contacts.some(contact => contact.verified) && <T kind="caption">You can plan a journey without selecting a contact.</T>}<Button title="Save journey" icon={Route} busy={busy} disabled={Object.values(form).some(value => value.trim().length < 2)} onPress={save} /></Card>}
    <Note icon={LockKeyhole}>Demo journeys save your status and check-ins. Background tracking and automatic alerts are not active.</Note>
    {data.journeys.length === 0 && <Card><Empty icon={Route} title="Your next journey starts here" description="Add a destination and an arrival time. You decide when to begin." /></Card>}
    {data.journeys.map(journey => <Card key={journey.id}><View style={s.between}><View style={[s.softIcon, { width: 39, height: 39 }]}><Route size={20} color={c.pine2} /></View><Badge label={statusLabel(journey.status)} tone={journey.status === 'OVERDUE' ? 'amber' : ['PLANNED', 'CANCELLED'].includes(journey.status) ? 'muted' : 'green'} /></View><T kind="heading">{journey.title}</T>{journey.anomaly && !journey.anomaly.acknowledged && <Note tone="amber">This journey needs a check-in: {statusLabel(journey.anomaly.type)}. Use Check in below to confirm you are safe.</Note>}<View style={{ gap: 10 }}><View style={s.row}><View style={{ width: 8, height: 8, borderRadius: 4, borderColor: c.pine2, borderWidth: 2 }} /><T style={s.flex}>{journey.origin}</T></View><View style={s.row}><MapPin size={13} color={c.pine2} style={{ marginLeft: -2 }} /><T kind="label" style={s.flex}>{journey.destination}</T></View></View><View style={s.divider} /><View style={s.between}><T kind="caption">Expected arrival</T><T kind="caption" style={{ color: c.ink }}>{dateLabel(journey.expectedArrival)} · {timeLabel(journey.expectedArrival)}</T></View>{journey.status === 'PLANNED' && <Button title="Start journey" icon={Navigation} busy={busy} onPress={() => void run(() => apiRequest(`/journeys/${journey.id}/start`, { method: 'POST', body: '{}' }), 'Your demo journey has started.')} />}{['ACTIVE', 'OVERDUE'].includes(journey.status) && <><Button title="I’ve arrived safely" icon={CheckCircle2} busy={busy} onPress={() => void run(() => apiRequest(`/journeys/${journey.id}/end`, { method: 'POST', body: '{}' }), 'Arrival saved. Journey complete.')} /><View style={s.row}><Button title="Check in" tone="soft" busy={busy} style={s.flex} onPress={() => void run(() => apiRequest(`/journeys/${journey.id}/check-in`, { method: 'POST', body: JSON.stringify({ message: 'I am safe' }) }), 'Your check-in is saved.')} /><Button title="+15 minutes" tone="outline" busy={busy} style={s.flex} onPress={() => void run(() => apiRequest(`/journeys/${journey.id}/extend`, { method: 'POST', body: JSON.stringify({ minutes: 15 }) }))} /></View></>}</Card>)}
  </>;
}

export function TimerScreen({ data, busy, run }: ScreenProps) {
  const [minutes, setMinutes] = useState(15);
  const [label, setLabel] = useState('Check on me');
  const active = data.timers.filter(timer => ['RUNNING', 'GRACE'].includes(timer.status));
  const past = data.timers.filter(timer => !['RUNNING', 'GRACE'].includes(timer.status));
  return <><PageHeading eyebrow="Quiet support" title="Safety timer" description="“Check on me in X minutes.” A little extra accountability for your everyday moments." /><Card><View style={s.row}><View style={[s.softIcon, { backgroundColor: c.violetSoft }]}><Timer size={24} color={c.violet} /></View><View style={s.flex}><T kind="heading">Set a quiet check-in</T><T kind="caption">No location sharing needed</T></View></View><Choices options={[5, 10, 15, 30]} value={minutes} onChange={setMinutes} /><Field label="What’s your plan?" value={label} onChangeText={setLabel} placeholder="Walking home" maxLength={80} /><Button title={`Start ${minutes}-minute timer`} icon={Timer} busy={busy} disabled={label.trim().length < 2} onPress={() => void run(() => apiRequest('/timers', { method: 'POST', body: JSON.stringify({ durationMinutes: minutes, label }) }))} /></Card>
    <Note icon={Clock3} tone="amber">Demo timers count down here and save your check-in. Automatic reminders and contact escalation are not connected yet.</Note>
    {active.map(timer => <Card key={timer.id}><SectionTitle eyebrow="Your active timer" title={timer.label} />{timer.status === 'GRACE' && <Note tone="amber">Your timer has ended. Please confirm you are safe during the grace period.</Note>}<View style={{ alignItems: 'center', paddingVertical: 7 }}><TimerClock timer={timer} large /></View><Button title="I’m safe · Confirm check-in" icon={Check} busy={busy} onPress={() => void run(() => apiRequest(`/timers/${timer.id}/confirm`, { method: 'POST', body: '{}' }), 'Your check-in is saved.')} /><View style={s.row}><Button title="+5 minutes" tone="soft" style={s.flex} busy={busy} onPress={() => void run(() => apiRequest(`/timers/${timer.id}/extend`, { method: 'POST', body: JSON.stringify({ minutes: 5 }) }))} /><Button title="Cancel timer" tone="outline" style={s.flex} busy={busy} onPress={() => void run(() => apiRequest(`/timers/${timer.id}/cancel`, { method: 'POST', body: '{}' }))} /></View></Card>)}
    {past.length > 0 && <Card><SectionTitle eyebrow="Previous check-ins" title="Timer history" />{past.slice(0, 8).map(timer => <View key={timer.id} style={s.row}><Clock3 size={18} color={c.violet} /><View style={s.flex}><T kind="label">{timer.label}</T><T kind="caption">{dateLabel(timer.createdAt)} · {timer.durationMinutes} minutes</T></View><Badge label={statusLabel(timer.status)} tone={timer.status === 'CONFIRMED' ? 'green' : 'muted'} /></View>)}</Card>}
  </>;
}

export function NearbyScreen() {
  return <><PageHeading eyebrow="Support around you" title="Nearby help" description="Find a place or person who can help. Open a current search in your maps app." /><Card style={{ backgroundColor: c.pine, borderColor: c.pine }}><LifeBuoy size={30} color={c.mintStrong} /><T kind="title" style={{ color: c.white }}>Keep support close.</T><T style={{ color: '#bdd8ce' }}>For immediate help in India, you can open your phone’s emergency dialer.</T><Button title="Open dialer · 112" icon={Phone} tone="soft" onPress={() => void openLink('tel:112')} /></Card>{[{ title: 'Hospitals', copy: 'Find nearby medical facilities', query: 'hospitals', icon: Hospital }, { title: 'Police stations', copy: 'Find local police assistance', query: 'police stations', icon: ShieldCheck }, { title: 'Pharmacies', copy: 'Search nearby pharmacies', query: 'pharmacies', icon: Plus }].map(item => <Pressable key={item.title} accessibilityRole="button" onPress={() => void openLink(mapsSearch(item.query))}><Card><View style={s.row}><View style={[s.softIcon, { backgroundColor: c.amberSoft }]}><item.icon size={22} color={c.amber} /></View><View style={s.flex}><T kind="heading">{item.title}</T><T kind="caption">{item.copy}</T></View><ArrowRight size={18} color={c.faint} /></View></Card></Pressable>)}<Note icon={MapPin}>Maps will use its own location permission. Opening a search does not share your location with your ABHAYA contacts.</Note></>;
}

export function HistoryScreen({ data, notificationsOnly = false }: ScreenProps & { notificationsOnly?: boolean }) {
  const entries = notificationsOnly ? data.notifications.map(item => ({ id: item.id, title: item.title, detail: item.body, date: item.createdAt, icon: Bell })) : [
    ...data.journeys.map(item => ({ id: item.id, title: item.title, detail: `${item.origin} → ${item.destination} · ${statusLabel(item.status)}`, date: item.createdAt, icon: Route })),
    ...data.timers.map(item => ({ id: item.id, title: item.label, detail: `${item.durationMinutes} minute timer · ${statusLabel(item.status)}`, date: item.createdAt, icon: Timer })),
    ...data.history.emergencies.map(item => ({ id: item.id, title: 'Emergency session', detail: statusLabel(item.status), date: item.createdAt, icon: ShieldCheck })),
    ...data.history.checkIns.map(item => ({ id: item.id, title: 'Safety check-in', detail: item.message || 'I am safe', date: item.createdAt, icon: CheckCircle2 })),
    ...data.notifications.map(item => ({ id: item.id, title: item.title, detail: item.body, date: item.createdAt, icon: Bell })),
  ].sort((a, b) => b.date.localeCompare(a.date));
  return <><PageHeading eyebrow="Your safety pulse" title={notificationsOnly ? 'Notifications' : 'Safety history'} description="A simple record of your journeys, check-ins, and demo updates." /><Note>Notification records in this demo do not indicate that a real message was sent.</Note><Card>{entries.length ? entries.map((item, index) => <View key={item.id} style={[s.row, { alignItems: 'flex-start', paddingVertical: 10 }, index > 0 && { borderTopWidth: 1, borderTopColor: c.line }]}><View style={[s.softIcon, { width: 35, height: 35 }]}><item.icon size={17} color={c.pine2} /></View><View style={s.flex}><T kind="label">{item.title}</T><T kind="caption" style={{ marginTop: 4 }}>{item.detail}</T><T kind="caption" style={{ marginTop: 6, color: c.faint, fontSize: 10 }}>{dateLabel(item.date)} · {timeLabel(item.date)}</T></View></View>) : <Empty title="A fresh start" description="Your activity will appear here as you use your safety tools." />}</Card></>;
}
