import { useEffect, useState, type JSX, type ReactNode } from 'react';
import { ArrowRight, Check, ChevronDown, CircleHelp, LoaderCircle, MapPin, X } from './icons';

export function Logo({ compact = false }: { compact?: boolean }) {
  return <div className={`brand-mark ${compact ? 'brand-mark--compact' : ''}`}><span className="brand-orb"><span>✦</span></span><span className="brand-type"><strong>ABHAYA</strong><small>1107</small></span></div>;
}

export function Button({ children, variant = 'primary', size = 'md', icon, loading, className = '', type = 'button', onClick, disabled }: { children: ReactNode; variant?: 'primary' | 'soft' | 'outline' | 'ghost' | 'danger' | 'dark'; size?: 'sm' | 'md' | 'lg'; icon?: ReactNode; loading?: boolean; className?: string; type?: 'button' | 'submit' | 'reset'; onClick?: () => void; disabled?: boolean }) {
  return <button type={type} className={`btn btn--${variant} btn--${size} ${className}`} onClick={onClick} disabled={disabled || loading}>{loading ? <LoaderCircle className="spin" size={16} /> : icon}{children}</button>;
}

export function IconButton({ label, children, onClick, className = '', danger = false }: { label: string; children: ReactNode; onClick?: () => void; className?: string; danger?: boolean }) {
  return <button className={`icon-button ${danger ? 'icon-button--danger' : ''} ${className}`} aria-label={label} title={label} onClick={onClick}>{children}</button>;
}

export function Pill({ children, tone = 'neutral', dot = false }: { children: ReactNode; tone?: 'success' | 'warning' | 'danger' | 'info' | 'neutral' | 'purple'; dot?: boolean }): JSX.Element {
  return <span className={`pill pill--${tone}`}>{dot && <span className="pill-dot" />}{children}</span>;
}

export function Card({ children, className = '', onClick }: { children: ReactNode; className?: string; onClick?: () => void }) { return <section className={`card ${className}`} onClick={onClick}>{children}</section>; }
export function CardHeader({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <div className="card-header"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h3>{title}</h3></div>{action}</div>; }
export function Field({ label, hint, error, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string; hint?: string; error?: string }) { return <label className="field"><span className="field-label">{label}</span><input {...props} />{hint && <span className="field-hint">{hint}</span>}{error && <span className="field-error">{error}</span>}</label>; }
export function SelectField({ label, children, ...props }: React.SelectHTMLAttributes<HTMLSelectElement> & { label: string }) { return <label className="field"><span className="field-label">{label}</span><span className="select-wrap"><select {...props}>{children}</select><ChevronDown size={16} /></span></label>; }
export function Toggle({ label, description, checked, onChange }: { label: string; description?: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="toggle-row"><span><strong>{label}</strong>{description && <small>{description}</small>}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span className="toggle-track"><span /></span></label>; }
export function EmptyState({ icon, title, description, action }: { icon?: ReactNode; title: string; description: string; action?: ReactNode }) { return <div className="empty-state">{icon && <div className="empty-icon">{icon}</div>}<h3>{title}</h3><p>{description}</p>{action}</div>; }
export function StatusDot({ status }: { status: string }) { const tone = status.includes('ACTIVE') || status === 'RUNNING' || status === 'DELIVERED' || status === 'COMPLETED' ? 'success' : status.includes('CANCEL') || status === 'FAILED' ? 'danger' : status === 'GRACE' || status === 'OVERDUE' || status === 'PARTIAL' ? 'warning' : 'info'; return <Pill tone={tone} dot>{status.replace(/_/g, ' ')}</Pill>; }
export function Modal({ title, children, onClose, width = '480px' }: { title: string; children: ReactNode; onClose: () => void; width?: string }) { return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="modal" style={{ maxWidth: width }} role="dialog" aria-modal="true"><div className="modal-header"><h2>{title}</h2><IconButton label="Close" onClick={onClose}><X size={18} /></IconButton></div>{children}</div></div>; }
export function Toast({ message, tone = 'success', onClose }: { message: string; tone?: 'success' | 'danger' | 'info'; onClose: () => void }) { useEffect(() => { const timer = window.setTimeout(onClose, 5000); return () => window.clearTimeout(timer); }, [onClose]); return <div className={`toast toast--${tone}`}><span className="toast-icon">{tone === 'success' ? <Check size={16} /> : <CircleHelp size={16} />}</span><span>{message}</span><button onClick={onClose}><X size={14} /></button></div>; }
export function Skeleton({ width = '100%', height = '16px' }: { width?: string; height?: string }) { return <span className="skeleton" style={{ width, height }} />; }
export function MiniMap({ lat = 17.4239, lng = 78.4071, markers = 3, active = false }: { lat?: number; lng?: number; markers?: number; active?: boolean }) { return <div className={`mini-map ${active ? 'mini-map--active' : ''}`}><div className="map-grid" /><div className="map-road map-road--one" /><div className="map-road map-road--two" /><div className="map-road map-road--three" /><div className="map-label map-label--top">Jubilee Hills</div><div className="map-label map-label--bottom">Banjara Hills</div><span className="map-you" style={{ left: `${40 + (Math.abs(lat * 100) % 18)}%`, top: `${43 + (Math.abs(lng * 100) % 14)}%` }}><span /></span>{Array.from({ length: markers }).map((_, index) => <span className="map-marker" key={index} style={{ left: `${20 + index * 24}%`, top: `${24 + (index % 2) * 35}%` }}><MapPin size={15} /></span>)}<div className="map-controls"><button aria-label="Map zoom">+</button><button aria-label="Map zoom out">−</button></div></div>; }
export function TimeAgo({ date }: { date?: string }) { if (!date) return <>—</>; const diff = Math.max(0, Date.now() - new Date(date).getTime()); const minutes = Math.floor(diff / 60000); if (minutes < 1) return <>just now</>; if (minutes < 60) return <>{minutes}m ago</>; const hours = Math.floor(minutes / 60); if (hours < 24) return <>{hours}h ago</>; return <>{Math.floor(hours / 24)}d ago</>; }
export function SectionHeading({ kicker, title, description, action }: { kicker?: string; title: string; description?: string; action?: ReactNode }) { return <div className="section-heading"><div>{kicker && <div className="eyebrow">{kicker}</div>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div>; }
export function LocationBadge({ live = false }: { live?: boolean }) { return <span className="location-badge"><span className={live ? 'live-dot' : 'location-dot'} />{live ? 'Location sharing live' : 'Location sharing off'}</span>; }
export function QuickLink({ icon, title, description, onClick, accent = 'green' }: { icon: ReactNode; title: string; description: string; onClick: () => void; accent?: string }) { return <button className={`quick-link quick-link--${accent}`} onClick={onClick}><span className="quick-link-icon">{icon}</span><span><strong>{title}</strong><small>{description}</small></span><ArrowRight size={15} /></button>; }
